# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python#publishing-to-package-registries

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
name: Upload to PYPI

on:
  push:
    tags:
      - '*.*.*.*'

permissions:
  contents: read

jobs:
  build-n-publish:

    name: Build and upload to PIPY
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Set up Python 3.8
      uses: actions/setup-python@v3
      with:
        python-version: '3.8'

    - name: Install pypa/setuptools
      run: |
        python -m pip install --upgrade pip
        pip install build
        pip install wheel
    # - name: Extract tag name
    #   id: tag
    #   run: echo ::set-output name=TAG_NAME::$(echo $GITHUB_REF | cut -d / -f 3)

    - name: Update version in setup.py
      run: sed -i "s/{{VERSION_PLACEHOLDER}}/${{ github.ref_name }}/g" setup.py

    - name: Build package
      # run: python -m build
      run: python setup.py sdist bdist_wheel

    - name: Publish to PYPI
      uses: pypa/gh-action-pypi-publish@master
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}
